--1
SELECT *
FROM EMP;

--2
SELECT *
FROM EMP
WHERE ENAME > 'P%'
ORDER BY ENAME;

--3
SELECT *
FROM EMP
WHERE HIREDATE > '1983-01-01' AND DEPTNO = 20
ORDER BY HIREDATE;

--4
SELECT ENAME,DNAME
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

--5
INSERT INTO EMP(EMPNO, ENAME)
VALUES(9000,'BART')

INSERT INTO EMP(EMPNO, ENAME)
VALUES(7654,'DUPLICATE')

--6
DELETE FROM DEPT
WHERE DEPTNO = 20;
--DEPTNO IS THE PRIMARY KEY


--7 + 8
INSERT INTO EMP
                         (EMPNO, ENAME, DEPTNO)
VALUES        (9001, 'JOE', 50);


--9
INSERT INTO DEPT
                         (DEPTNO, DNAME, LOC)
VALUES        (50, 'SALES', 'DUBLIN');

--10
UPDATE       EMP
SET                 HIREDATE = CONVERT(DATETIME, '2005-09-19 00:00:00', 102), SAL = 10000
WHERE (EMPNO = 9001);


