--1
SELECT *
FROM EMP;

--2  SELECT TOP(1000) EMPNO, ...
SELECT *
FROM EMP
WHERE ENAME > 'P%'
ORDER BY ENAME;

--3
SELECT *
FROM EMP
WHERE HIREDATE > '01-JAN-1983' AND DEPTNO = 20
ORDER BY HIREDATE;

--4
SELECT E.*,DNAME AS DEPT_NAME
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
-- INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

--5
--INSERT INTO EMP
--VALUES(9000,'BART',null,null,null,null,null,null);
INSERT INTO EMP(EMPNO, ENAME)
VALUES(9000,'BART');

INSERT INTO EMP(EMPNO, ENAME)
VALUES(7654,'DUPLICATE');

--6
DELETE FROM DEPT
WHERE DEPTNO = 20;
--DEPTNO IS THE PRIMARY KEY

--7 + 8
INSERT INTO EMP(EMPNO, ENAME, DEPTNO)
VALUES(9001, 'JOE', 50);
--Error Violates PK

--9
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(50, 'SALES', 'DUBLIN');

--10
UPDATE EMP
SET HIREDATE = '19-SEP-2005',SAL = 10000
WHERE (EMPNO = 9001);